INSERT INTO `trialsite` (`facilityName`, `address1`, `address2`, `address3`, `address4`, `address5`, `country`, `trialInfo_id`) VALUES
('University of Minnesota', '420 Delaware Street South East', '', '', 'Minneapolis', '55455', 'United States of America', 1),
('The Univeristy Of Texas Southwestern Medical Center At Dallas', '6000 Harry Hines Blvd.', '', '', 'Dallas', '75390', 'United States of America', 1),
('Sutter Cancer Center', '1020 29th Street', '', '', 'Sacramento', '95816', 'United States of America', 1),
('Southern Illinois Hematology/Oncology', '1052 Martin Luther King Drive', '', '', 'Centralia', '62801', 'United States of America', 1),
('Oncology Institute of Hope and Innovation', '15111 E. Whittier Blvd', '', '', 'Whittier', '90603', 'United States of America', 1),
('Oncology/Northeast Medical Center', '100 Medical Park Drive', '', '', 'Concord', '28025', 'United States of America', 1),
('Lake County Oncology And Hematology', '4100 Waterman Way', '', '', 'Tavares', '32778', 'United States of America', 1),
('New York University', '160 East 34th Street', '', '', 'New York', '10016', 'United States of America', 1),
('Lalita Pandit, Md, Inc', '11160 Warner Avenue', '', '', 'Fountain Valley', '92708', 'United States of America', 1),
('Metro Mn Ccop', '3800 Park Nicollet Blvd.', '', '', 'St. Louis Park', '55416', 'United States of America', 1),
('University Of Colorado Hospital - Anschutz Medical Campus', '1635 N Ursula Street Ms F 732', '', '', 'Aurora', '80010', 'United States of America', 1),
('East Carolina University', '4W 54 Brody Building', '', '', 'Greenville', '27834', 'United States of America', 1),
('Jefferson Medical Oncology Associates', '925 Chestnut St Ste 220a', '', '', 'Philadelphia', '19107-4215', 'United States of America', 1),
('South Texas Institute Of Cancer', '1205 S 19th Street', '', '', 'Corpus Christi', '78405', 'United States of America', 1),
('East Valley Hematology Oncology Med Group - Disney Family Cancer Center', '181 South Buena Vista Street', '', '', 'Burbank', '91505', 'United States of America', 1),
('University of Sheffield', '101 Western Bank', '', '', 'Sheffield', 'S10 2TN', 'United Kingdom', 1),
('Cape Cornwall Surgery', '212 Market St St Just', '', '', 'Penzance', ' TR19 7HX', 'United Kingdom', 1),
('Brannel Surgery', '58 Rectory Rd', '', '', 'St Austell', 'PL26 7RL', 'United Kingdom', 1),
('The Crouch Oak Family Practice', '45 Station Rd', '', '', 'Addelstone', 'KT15 2BH', 'United Kingdom', 1),
('Waterloo Medical Centre', '5 Lower Marsh', '', '', 'London', 'SE1 7RJ', 'United Kingdom', 1),
('Castle Mile Group Practice', '1 Vince\'s rd', '', '', 'Diss', 'IP224AY', 'United Kingdom', 1),
('Atherstone Surgery', '1 Ratcliffe Rd', '', '', 'Atherstone', 'CV91EU', 'United Kingdom', 1),
('Sheepcot Medical Centre', '6 Cunningham Way', '', '', 'Watford', 'WD25 7NL', 'United Kingdom', 1),
('Bradford Road Medical Centre', '60 Bradford Rd', '', '', 'Trowbridge', 'BA14 9AR', 'United Kingdom', 1),
('Ashgate Medical Practice', 'Ashgate Manor', '', '', 'Chesterfield', 'S40 4AA', 'United Kingdom', 1);